### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by devarsh10**
Added little bit of information. Like where to install dependencies and git clone.

### CODE REVIEW

**Review by andrewdmaclean — CHANGES_REQUESTED** [review]
Hey @devarsh10 👋 

Thanks for the submission 🙏 

So these officially supported Quick Starts are really focused on allowing you to use the template feature of GitHub to make a copy of the repository that way.

With that in mind, I am wondering if you might have another suggestion?

image

**Comment by devarsh10** [comment]
No suggestions. But will create pull request if I get any.
Regards

**Comment by andrewdmaclean** [comment]
Alright, so for now then I am going to close this PR but thank you so much for the contribution and feel free to re-open if you have other changes in the future.

**Comment by devarsh10** [comment]
Okay

**Pull request closed without merging**
