### PR TITLE
Update to python381-cancel

### PR DESCRIPTION
**Pull request by jonknoll**
It concerned that the instructions for the python snake were still using python 2.7, especially since it is probably the most popular language to use for this competition, and python 2 has gone end of life. It is also very common for someone just starting out to download the latest version of the software, and they may get tripped up with a python 2.7 example. As such, I have updated the starter snake to run with the latest python (3.8.1). I have tested both locally and on heroku.

A summary of my changes:
-updated readme.md file with the latest links and changes required for the new version.
-switched from gunicorn to cherrypy as the webserver. It has a little better performance (https://www.appdynamics.com/blog/engineering/a-performance-analysis-of-python-wsgi-servers-part-2/) and also I wanted to ensure that the same web server was being used both locally and on heroku. And I couldn't get gunicorn to run locally on windows.
-due to the new import rule where you have to use a dot to specify "same directory", I had to make a little starter script so you could run the server locally from the root. So starting the server locally changed from "python app/main.py" to "python run.py"

Hopefully these changes will help! I also plan to create a pull request for the python tutorial for windows.
cheers,
Jon
PS This is my first pull request ever!

### CODE REVIEW

**Comment by bvanvugt** [comment]
@jonknoll Thanks for this, bumping to Python3 was on our list.

The only part of this that concerns me is the move from Gunicorn to CherryPy. I don't know enough about CherryPy to make this call, maybe @dlsteuer, @joram, or @coldog do... specifically we use gunicorn because of its concurrency model. Does CherryPy support worker pools / concurrent request processing?

Either way - could you split this into two PRs, one moving to python 3 and another moving to CherryPy?

**Comment by jonknoll** [comment]
@bvanvugt I actually wanted to submit this as 2 PRs.. The issue is gunicorn was crashing on heroku and I didn't know how to fix it. And I couldn't debug it locally because gunicorn needs the built-in python fcntl library which the windows version of python doesn't seem to have. The cherrypy proposed changes are what I ran with last year. It supports concurrent requests (pool of 10 threads by default I believe).

**Comment by jonknoll** [comment]
I've looked around the interwebs and it appears that gunicorn only works on unix systems and not windows. I cannot decipher the debug messages from the heroku logs, and I can't debug it locally because I only have Windows. So I can't separate my python updates from the switch to cherrypy.

**Comment by blakmajk** [comment]
I used cherrypy/cheroot for my snake last year for the same reason of windows compatibility.  It's a significant performance improvement from the default bottle single-threaded one, and I didn't see any problems with it on Heroku when I used it there as well.  It handled multiple games running at once without issue for me.  

It is a threaded worker pool, and not a forked one like gunicorn, but I feel that shouldn't be a problem for a starter snake.

**Comment by jonknoll** [comment]
I don't know how to cancel pull request, but cancel this one...
I found a way to get gunicorn working on python 3. Please see my newer 2 pull requests.

**Pull request closed without merging**
